### ISSUE TITLE
Soak is broken with new parser

### ISSUE THREAD

**Issue by gregsexton** [SkipLabs/skip#29]
`make test-soak` results in the following. Doesn't support naming expressions? cc @beauby 

```
Running expectation checks for checkpoint { client: 1, latest_id: 30 }
file:///skfs/build/package/skdb/dist/sk_types.mjs:195
                let error = new SkRuntimeExit(exitCode, message?.trim());
                            ^

SkRuntimeExit [Error]: select client, value >= @latest_id as check
                                      ^
                                      |
                                       ----- ERROR
Error: line 1, character 38:
Unexpected token CHECK: expected IDENTIFIER
Internal error: select client, value >= @latest_id as check
                                      ^
                                      |
                                       ----- ERROR
Error: line 1, character 38:
Unexpected token CHECK: expected IDENTIFIER
    at Utils.main (file:///skfs/build/package/skdb/dist/sk_types.mjs:195:29)
    at SKDBSyncImpl.main [as runLocal] (file:///skfs/build/package/skdb/dist/skdb_skdb.mjs:208:33)
    at file:///skfs/build/package/skdb/dist/skdb_database.mjs:78:29
    at SKDBSyncImpl.runner (file:///skfs/build/package/skdb/dist/skdb_skdb.mjs:199:30)
    at SKDBSyncImpl.exec (file:///skfs/build/package/skdb/dist/skdb_database.mjs:76:25)
    at SKDBImpl.exec (file:///skfs/build/package/skdb/dist/skdb_database.mjs:197:46)
    at check_expectation (file:///skfs/sql/server/test/soak_client.mjs:154:30)
    at check_expectations (file:///skfs/sql/server/test/soak_client.mjs:204:3)
    at file:///skfs/sql/server/test/soak_client.mjs:356:9
    at file:///skfs/build/package/skdb/dist/skdb_skdb.mjs:238:21 {
  code: 0,
  cause: SkException [Error]: Unexpected token CHECK: expected IDENTIFIER
      at Utils.ethrow (file:///skfs/build/package/skdb/dist/sk_types.mjs:328:23)
      at LinksImpl.js_throw (file:///skfs/build/package/skdb/dist/sk_runtime.mjs:30:53)
      at toWasm.js_throw (file:///skfs/build/package/skdb/dist/sk_runtime.mjs:128:58)
      at SKIP_throw (wasm://wasm/00dc0932:wasm-function[2247]:0x34921)
      at SQLParser.Parser__errorUnexpectedToken (wasm://wasm/00dc0932:wasm-function[4707]:0xbd0a6)
      at sk.SQLParser_Parser__parseSelectResult (wasm://wasm/00dc0932:wasm-function[5409]:0xf2cf3)
      at sk.SQLParser_Parser__parseSelectResults (wasm://wasm/00dc0932:wasm-function[5407]:0xf27af)
      at sk.SQLParser_Parser__parseSelectCoreQuery (wasm://wasm/00dc0932:wasm-function[3694]:0x8035a)
      at sk.SQLParser_Parser__parseSelectCore__Closure0__call (wasm://wasm/00dc0932:wasm-function[3693]:0x802c2)
      at SQLParser.Parser__parse_one_of_keywords (wasm://wasm/00dc0932:wasm-function[4714]:0xbd644) {
    cause: SkRuntimeExit [Error]: select client, value >= @latest_id as check
                                          ^
                                          |
                                           ----- ERROR
    Error: line 1, character 38:
    Unexpected token CHECK: expected IDENTIFIER
    
        at Utils.exit [as SKIP_throw_cruntime] (file:///skfs/build/package/skdb/dist/sk_types.mjs:89:19)
        at toWasm.SKIP_throw_cruntime (file:///skfs/build/package/skdb/dist/sk_runtime.mjs:129:58)
        at SKIP_exit (wasm://wasm/00dc0932:wasm-function[4663]:0xb8480)
        at sk.skipExit.6 (wasm://wasm/00dc0932:wasm-function[3502]:0x76f58)
        at sk.SKDB_main__Closure0__call__Closure1__call (wasm://wasm/00dc0932:wasm-function[3495]:0x76a28)
        at sk.SKDB_main__Closure0__call (wasm://wasm/00dc0932:wasm-function[4116]:0x95443)
        at sk.vtry__Closure0__call.17 (wasm://wasm/00dc0932:wasm-function[3458]:0x74fcd)
        at SKIP_call0 (wasm://wasm/00dc0932:wasm-function[5777]:0x10814a)
        at Utils.call (file:///skfs/build/package/skdb/dist/sk_types.mjs:276:33)
        at Utils.etry [as SKIP_etry] (file:///skfs/build/package/skdb/dist/sk_types.mjs:293:29) {
      code: 1
    }
  }
}
```

**Comment by beauby** [comment]
That's because `CHECK` is an SQL keyword. I'll send a PR to relax the constraint on aliases so that keywords can be used, though in general it's suggested to quote keywords when used as identifier.

**Comment by gregsexton** [comment]
Oh sorry, of course, I didn't think about check constraints. The error is pretty clear in hindsight too. My bad.

I can rename in the tests. FWIW sqlite doesn't like this either:

```
sqlite> select 3 > 2 as check;
Error: in prepare, near "check": syntax error (1)
```
